B = ex04
CC = c++
FLAG = -Wall -Werror -Wextra -std=c++98 -g3

SRC = main.cpp
OBJ = $(SRC:.cpp=.o)

all: $(B)

$(B): $(OBJ)
	$(CC) $(FLAG) -o $(B) $(OBJ)

%.o: %.cpp
	$(CC) $(FLAG) -c $< -o $@

clean:
	rm -rf $(OBJ)

fclean: clean
	rm -rf $(B)

re: fclean all
